export const pokemonTypes = {
  // Async
  POKEMON_FETCH_ASYNC: "POKEMON_FETCH_ASYNC",
  // Sync
  POKEMON_START_FETCHING: "POKEMON_START_FETCHING",
  POKEMON_STOP_FETCHING: "POKEMON_STOP_FETCHING",
  POKEMON_FILL: "POKEMON_FILL",
  POKEMON_FETCHING_ERROR: "POKEMON_FETCHING_ERROR",
} as const;
